<?php

/**
 * This is the model base class for the table "tbl_room_directory".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RoomDirectory".
 *
 * Columns in table "tbl_room_directory" available as properties of the model,
 * followed by relations of table "tbl_room_directory" available as properties of the model.
 *
 * @property integer $id
 * @property string $room_id
 * @property string $company_id
 * @property string $directory
 *
 * @property Rooms $room
 */
abstract class BaseRoomDirectory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_room_directory';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'RoomDirectory|RoomDirectories', $n);
	}

	public static function representingColumn() {
		return 'directory';
	}

	public function rules() {
		return array(
			array('room_id, company_id, directory', 'required'),
			array('room_id, company_id', 'length', 'max'=>11),
			array('directory', 'length', 'max'=>255),
			array('id, room_id, company_id, directory', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'room' => array(self::BELONGS_TO, 'Rooms', 'room_id'),
			//'presentations' => array(self::HAS_MANY,'Presentations','room_dir_id')
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'company_id' => null,
			'room_id' => null,
			'directory' => Yii::t('app', 'Directory'),
			'room' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('room_id', $this->room_id);
		$criteria->compare('company_id', $this->company_id);
		$criteria->compare('directory', $this->directory, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}